import json
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from typing import Optional, Dict, Any

from utils.deps import get_current_user
from utils.n8n import generate_plan
from database import get_pool

router = APIRouter()

class PlanGenerateRequest(BaseModel):
    quiz_score: Optional[int] = None

@router.post("/generate")
async def create_plan(request: PlanGenerateRequest, current_user: dict = Depends(get_current_user)):
    """Generate a 7-day action plan based on user profile and optional quiz score."""
    pool = get_pool()
    
    # 1. Fetch user profile
    async with pool.acquire() as conn:
        profile = await conn.fetchrow("SELECT * FROM profiles WHERE user_id = $1", current_user["id"])
        
    if not profile:
        raise HTTPException(status_code=400, detail="Profile not found. Please complete your profile first.")
        
    profile_dict = dict(profile)
    # Remove large/unnecessary fields for LLM context to save tokens if needed
    if "resume_path" in profile_dict:
        del profile_dict["resume_path"]

    # 2. Call n8n to generate plan
    quiz_data = {"score": request.quiz_score} if request.quiz_score is not None else {}
    plan_result = await generate_plan(current_user, profile_dict, quiz_data)

    if "error" in plan_result:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=plan_result["error"]
        )

    # 3. Save to database
    plan_json_str = json.dumps(plan_result)
    async with pool.acquire() as conn:
        plan_id = await conn.fetchval("""
            INSERT INTO plans (user_id, plan_json, quiz_score)
            VALUES ($1, $2, $3)
            RETURNING id
        """, current_user["id"], plan_json_str, request.quiz_score)

    return {"id": plan_id, "plan": plan_result}


@router.get("/")
async def get_latest_plan(current_user: dict = Depends(get_current_user)):
    """Get the user's most recently generated 7-day plan."""
    pool = get_pool()
    async with pool.acquire() as conn:
        plan = await conn.fetchrow("""
            SELECT id, plan_json, completed_tasks, quiz_score, created_at 
            FROM plans 
            WHERE user_id = $1 
            ORDER BY created_at DESC 
            LIMIT 1
        """, current_user["id"])
        
    if not plan:
        raise HTTPException(status_code=404, detail="No action plan found. Please generate one first.")
        
    return {
        "id": plan["id"],
        "plan": json.loads(plan["plan_json"]),
        "completed_tasks": json.loads(plan["completed_tasks"]) if plan["completed_tasks"] else {},
        "quiz_score": plan["quiz_score"],
        "created_at": plan["created_at"].isoformat()
    }

class ProgressUpdateRequest(BaseModel):
    completed_tasks: dict

@router.put("/{plan_id}/progress")
async def update_plan_progress(plan_id: int, request: ProgressUpdateRequest, current_user: dict = Depends(get_current_user)):
    """Update the checked/unchecked progress state of a specific plan."""
    pool = get_pool()
    async with pool.acquire() as conn:
        owner = await conn.fetchval("SELECT user_id FROM plans WHERE id = $1", plan_id)
        if owner != current_user["id"]:
            raise HTTPException(status_code=403, detail="Not authorized to update this plan")
            
        await conn.execute(
            "UPDATE plans SET completed_tasks = $1 WHERE id = $2",
            json.dumps(request.completed_tasks), plan_id
        )
    return {"message": "Progress saved successfully"}


@router.get("/history")
async def get_plan_history(current_user: dict = Depends(get_current_user)):
    """Get history of all plans generated by the user."""
    pool = get_pool()
    async with pool.acquire() as conn:
        plans = await conn.fetch("""
            SELECT id, quiz_score, created_at 
            FROM plans 
            WHERE user_id = $1 
            ORDER BY created_at DESC
        """, current_user["id"])
        
    return [dict(p) for p in plans]
